# Uncomment the next line to define a global platform for your project
# platform :ios, ‘10.0’

target 'WalletPlus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '~> 7.0-beta'

  target 'WalletPlusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WalletPlusUITests' do
    # Pods for testing
  end

end
